import Link from "next/link";
import { FORM_OPTIONS } from "@/lib/form";
import { formatDate } from "@/lib/dates";
import { listLeads, type LeadFilters } from "@/lib/leads";

const statusLabels: Record<string, string> = { new: "جدید", contacted: "تماس گرفته شد", meeting_booked: "جلسه رزرو شد", unsuitable: "نامناسب", closed: "بسته‌شده" };

export default async function LeadsPage({ searchParams }: { searchParams: Promise<LeadFilters> }) {
  const filters = await searchParams;
  const { rows, page, total, pageSize } = await listLeads(filters);
  const exportParams = new URLSearchParams();
  for (const [key, value] of Object.entries(filters)) if (typeof value === "string" && value) exportParams.set(key, value);
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  return <><header className="admin-heading"><div><p className="eyebrow">مدیریت درخواست‌ها</p><h1>لیدها <span>{total}</span></h1></div><div className="export-links"><a href={`/admin/export?format=csv&${exportParams}`}>CSV</a><a href={`/admin/export?format=xlsx&${exportParams}`}>Excel</a></div></header><form className="filter-bar" action="/admin/leads"><input name="query" defaultValue={filters.query} placeholder="نام، باشگاه یا موبایل" /><select name="status" defaultValue={filters.status ?? ""}><option value="">همه وضعیت‌ها</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select name="qualified" defaultValue={filters.qualified ?? ""}><option value="">همه نتایج</option><option value="true">واجد شرایط</option><option value="false">نیازمند پیگیری</option></select><select name="role" defaultValue={filters.role ?? ""}><option value="">همه نقش‌ها</option>{FORM_OPTIONS.role.map((role) => <option key={role} value={role}>{role}</option>)}</select><select name="sort" defaultValue={filters.sort ?? "newest"}><option value="newest">جدیدترین ثبت</option><option value="oldest">قدیمی‌ترین ثبت</option><option value="score_high">بیشترین امتیاز</option><option value="score_low">کمترین امتیاز</option></select><input name="from" type="date" defaultValue={filters.from} /><input name="to" type="date" defaultValue={filters.to} /><button>اعمال فیلتر</button></form><div className="lead-table-wrap"><table className="lead-table"><thead><tr><th>متقاضی</th><th>باشگاه</th><th>امتیاز</th><th>وضعیت</th><th>ثبت</th><th /></tr></thead><tbody>{rows.length ? rows.map((lead) => <tr key={lead.id}><td><strong>{lead.fullName}</strong><small>{lead.phone}{lead.duplicateCount > 1 ? ` · ${lead.duplicateCount} ثبت` : ""}</small></td><td>{lead.gymName}<small>{lead.role} · {lead.members}</small></td><td><span className={lead.qualified ? "score good" : "score"}>{lead.score}</span></td><td><span className={`status status-${lead.status}`}>{statusLabels[lead.status]}</span></td><td>{formatDate(lead.createdAt)}</td><td><Link href={`/admin/leads/${lead.id}`}>مشاهده</Link></td></tr>) : <tr><td colSpan={6} className="empty-state">لیدی با این فیلتر پیدا نشد.</td></tr>}</tbody></table></div><nav className="pagination">{page > 1 ? <Link href={`/admin/leads?${new URLSearchParams({ ...Object.fromEntries(exportParams), page: String(page - 1) })}`}>بعدی</Link> : null}<span>صفحه {page} از {pageCount}</span>{page < pageCount ? <Link href={`/admin/leads?${new URLSearchParams({ ...Object.fromEntries(exportParams), page: String(page + 1) })}`}>قبلی</Link> : null}</nav></>;
}
